
/* Drop Tables */

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Cliente_Cuenta CASCADE
;

DROP TABLE IF EXISTS Transaccion CASCADE
;

DROP TABLE IF EXISTS Cuenta_Aliada CASCADE
;

/* Create Tables */

CREATE TABLE Cliente
(
	K_ID numeric(11) NOT NULL,
	N_NOMBRE varchar NOT NULL,
	N_APELLIDO varchar NOT NULL,
	Q_EDAD numeric(3) NOT NULL
)
;

CREATE TABLE Cuenta
(
	K_IDCUENTA serial NOT NULL,
	Q_SALDO money NOT NULL,
	N_TIPO varchar NOT NULL,
	Q_CONTRASENNA numeric(4) NOT NULL
)
;

CREATE TABLE Cliente_Cuenta
(
	K_ID numeric(11) NOT NULL,
	K_IDCUENTA integer NOT NULL
)
;

CREATE TABLE Transaccion
(
    K_IDTX serial NOT NULL,
	K_IDCUENTA integer NOT NULL,
	D_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	O_DESCRIPCION varchar NOT NULL,
	O_TIPO varchar NOT NULL
)
;

CREATE TABLE Cuenta_Aliada
(
	K_IDCUENTA integer NOT NULL,
	K_IDCUENTAALIADA integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (K_ID)
;

ALTER TABLE Cuenta ADD CONSTRAINT PK_Cuenta
	PRIMARY KEY (K_IDCUENTA)
;

ALTER TABLE CLIENTE_CUENTA ADD CONSTRAINT PK_CLIENTE_CUENTA
	PRIMARY KEY (K_IDCUENTA)
;

CREATE INDEX IXFK_CLIENTE_CUENTA_Cliente ON CLIENTE_CUENTA (K_ID ASC)
;

CREATE INDEX IXFK_CLIENTE_CUENTA_Cuenta ON CLIENTE_CUENTA (K_IDCUENTA ASC)
;

ALTER TABLE Transaccion ADD CONSTRAINT PK_Transaccion
	PRIMARY KEY (K_IDTX)
;

ALTER TABLE Cuenta_Aliada ADD CONSTRAINT PK_CUENTA_ALIADA
	PRIMARY KEY (K_IDCUENTA, K_IDCUENTAALIADA)
;

/* Create Foreign Key Constraints */

ALTER TABLE Transaccion ADD CONSTRAINT FK_Transaccion_Cuenta
	FOREIGN KEY (K_IDCUENTA) REFERENCES Cuenta (K_IDCUENTA) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE CLIENTE_CUENTA ADD CONSTRAINT FK_CLIENTE_CUENTA_Cliente
	FOREIGN KEY (K_ID) REFERENCES Cliente (K_ID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE CLIENTE_CUENTA ADD CONSTRAINT FK_CLIENTE_CUENTA_Cuenta
	FOREIGN KEY (K_IDCUENTA) REFERENCES Cuenta (K_IDCUENTA) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE CUENTA_ALIADA ADD CONSTRAINT FK_CUENTA_ALIADA_Cuenta
	FOREIGN KEY (K_IDCUENTA) REFERENCES Cuenta (K_IDCUENTA) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE CUENTA_ALIADA ADD CONSTRAINT FK_CUENTA_ALIADA_Aliada
	FOREIGN KEY (K_IDCUENTAALIADA) REFERENCES Cuenta (K_IDCUENTA) ON DELETE No Action ON UPDATE No Action
;

/* Alter sequence from Cuenta */

ALTER SEQUENCE cuenta_k_idcuenta_seq RESTART WITH 1000
;

SET TIME ZONE 'America/Bogota'
;