services:
    bank:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - 3000:3000
        links:
            - postgres:postgres
        depends_on:
            - postgres
        restart: always

    postgres:
        image: postgres
        env_file: .env
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres: